spring:
  application:
    name: web-application
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    #content-type: text/html
    mode: HTML5
  zipkin:
    base-url: http://localhost:9411
server:
  port: 9600
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE

eureka:
  instance:
    prefer-ip-address: true #注册服务的时候使用服务的ip地址ַ
  client:
    service-url:
      defaultZone: http://localhost:9500/eureka/